image: python:3.7-buster

before_script:
  - cat /etc/apt/sources.list
  - sed -i -e 's/httpredir\.debian\.org/deb.debian.org/g' /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - apt install -y git build-essential libssl-dev libffi-dev python3-dev
  - pip install pipenv
  - pipenv install --dev

stages:
  - Static analysis
  - Test
  - Deploy

flake8:
  stage: Static analysis
  script:
    - pipenv run pre-commit run flake8

pytest:
  stage: Test
  script:
    - pipenv run coverage run --source pynetics -m pytest tests
    - pipenv run coverage xml -o coverage.xml
    - pipenv run coverage report -m

pypi:
  stage: Deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - pipenv run python setup.py sdist bdist_wheel
    - pipenv run twine check dist/*
    - echo $TWINE_USERNAME
    - pipenv run twine upload dist/*
  only:
    - tags