image: python:3.7

before_script:
  - python --version
  - pip install pipenv
  - pipenv install --dev

stages:
  - Static analysis
  - Test
  - Deploy

flake8:
  stage: Static analysis
  script:
    - pipenv run flake8
  only:
    - master
    - devel

pytest:
  stage: Test
  script:
    - pipenv run coverage run --source pynetics -m pytest tests
    - pipenv run coverage xml -o coverage.xml
    - pipenv run coverage report -m
  only:
    - master
    - devel

pypi:
  stage: Deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - pipenv run python setup.py sdist bdist_wheel
    # - pipenv run twine check dist/*
    - pipenv run twine upload dist/*
  only:
    - tags